server:
  port: 8080

spring:
  application:
    name: game-mng-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      on-profile: prod
  security:
    user:
      name: admin
      password: admin

jdbc:
  url: jdbc:log4jdbc:postgresql://db-cls-stg-mgmt.c3uywyy2okpb.ap-northeast-2.rds.amazonaws.com:5432/cenlotsdb02?charSet=UTF-8&prepareThreshold=1&serverTimezone=Asia/Seoul
  username: cenapp02
  password: cenlotapp123!
  driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

jdbcSales:
  url: jdbc:log4jdbc:postgresql://db-cls-stg-sales.c3uywyy2okpb.ap-northeast-2.rds.amazonaws.com:5432/cenlotsdb01?charSet=UTF-8&prepareThreshold=1&serverTimezone=Asia/Seoul
  username: cenapp01
  password: cenlotapp123!
  driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy


eureka:
  instance:
    prefer-ip-address: true
    hostname: cenlots2024-discoveryserver-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}/eureka/
